version: '3.7'

services:
 monsaecommerce_app:
  env_file: .env
  build:
   args:
    user: ${USER}
    uid: ${UID}
   context: ./
   dockerfile: Dockerfile
  image: monsaecommerce_app
  container_name: monsaecommerce-app
  restart: unless-stopped
  working_dir: /usr/share/nginx/html
  volumes:
    - ${WORK_DIR_SRC}:/usr/share/nginx/html
  networks:
    - monsaecommerce-net

 monsaecommerce_www:
  image: nginx
  env_file: .env
  container_name: monsaecommerce-www
  restart: unless-stopped
  volumes:
  - ${WORK_DIR_SRC}:/usr/share/nginx/html
  - ${WORK_DIR}:/etc/nginx/conf.d
  ports:
  -  "8900:80"
  networks:
  - monsaecommerce-net

networks:
  monsaecommerce-net:
    name: monsaecommerce-net
    driver: bridge
